apiVersion: v1
kind: Service
metadata:
  name: rethinkdb
  labels:
    app: rethinkdb
    app.kubernetes.io/name: rethinkdb
spec:
  ports:
    - name: intracluster
      port: 29015
    - name: clients
      port: 28015
  clusterIP: None
  selector:
    app: rethinkdb